#!/bin/bash
if [ $1 == '*.mk'] || [$1 == '*.mkd']; then
	if [ $2 == '*.bbcode']; then
		scala -cp target/markdowntobbcode-1.3-SNAPSHOT.jar net.doxxx.markdowntobbcode.MarkdownToBBcode $1 $2
	fi
else
	echo ""
	echo " You have to specify a markdown file and a output.bbcode as output file"
	echo -e "\t e.g:"
	echo -e "\t $0 markdown-file output.bbcode"
	echo ""
fi
